### ISSUE TITLE
Missing world<->screen transforms.

### ISSUE THREAD

**Issue by toqueteos** [drakmaniso/glam#7]
Both GLU and GLM support this with `project` and `unProject` functions.

There's extensive docs on how both work:
http://www.opengl.org/sdk/docs/man2/xhtml/gluProject.xml
http://www.opengl.org/sdk/docs/man2/xhtml/gluUnProject.xml

Since these are common transformations I think they should be in on `glam`.

**Comment by drakmaniso** [comment]
I might add some of these utility functions at a later point, but currently they are not necessary since projection will be done in the shaders.
